# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Checkout repository
        uses: actions/checkout@main
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
         echo "Hello-5.1"
  
      - name: Run tests
        run: |
          echo "Hello-7.1"
          pwd
          cat test.pem
          echo "Hello-7.2"
          chmod 400 test.pem
          ssh -i "test.pem" ubuntu@ec2-54-82-107-162.compute-1.amazonaws.com << 'EOF'
           cp -r /home/ubuntu/home/* /var/www/Laravel-Demo
          EOF
          
           
          
        
         
          

        

      
