# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          
      - name: Run tests
        run: |
          echo "Hello-7"      
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          echo "H-8"
           
          
        
         
          

        

      
