# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          
      - name: Run tests
        run: |
          echo "Hello-7"      
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          echo "H-8"

          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $REMOTE_USER@REMOTE_HOST << 'EOF'
           cd /var/www/Laravel-Demo
           git pull origin main
           composer install --no-dev --prefer-dist --optimize-autoloader
           php artisan migrate --force
           php artisan config:cache
           php artisan route:cache
           php artisan view:cache
           sudo systemctl restart httpd # or nginx
          EOF
          
           
          
        
         
          

        

      
